Traceback (most recent call last):
  File "/home/sofista/miniconda3/envs/science/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/sofista/miniconda3/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/sofista/miniconda3/envs/science/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
  File "/home/sofista/miniconda3/envs/science/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/sofista/miniconda3/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/sofista/miniconda3/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/sofista/miniconda3/envs/science/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# define a vector of size 8 where the elements are integers between 1 and 8
A_vec = np.array([1,2,3,4,5,6,7,8])

# redefine the vector into a 3-rank tensors
A_ten = A_vec.reshape(2,2,2)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;66;03m# define a vector of size 8 where the elements are integers between 1 and 8[39;00m
[0;32m----> 2[0m A_vec [38;5;241m=[39m [43mnp[49m[38;5;241m.[39marray([[38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m3[39m,[38;5;241m4[39m,[38;5;241m5[39m,[38;5;241m6[39m,[38;5;241m7[39m,[38;5;241m8[39m])
[1;32m      4[0m [38;5;66;03m# redefine the vector into a 3-rank tensors[39;00m
[1;32m      5[0m A_ten [38;5;241m=[39m A_vec[38;5;241m.[39mreshape([38;5;241m2[39m,[38;5;241m2[39m,[38;5;241m2[39m)

[0;31mNameError[0m: name 'np' is not defined

